### ISSUE TITLE
Tab selected question

### ISSUE THREAD

**Issue by suyesh** [joshreed/jQuery-ScrollTabs#10]
Hi, 

lets say i have tab1, tab2, tab3, tab4, tab5. If in previous page i clicked tab4, i want the tabs to have tab4 in the first after the chevron icon. so basically tab1, tab2, tab3 hidden until i click on the left chevron to display them.

**Comment by joshreed** [comment]
I'm assuming you meant to "scroll" over to the selected tab. So this would not be a documented feature, but you definitely could "do" it:

Here's an example:
````
// Initialize the tab set
var tabSet = $('#tabSet').scrollTabs();

// Get the relevant positions
var currentScrollPos = $('#tabSet .scroll_tab_inner').scrollLeft();
var selectedElementPos = $('#tabsSet span.my-selected-element').position().left;

// Set the scroll position to what it "should" be
$('#tabsSet .scroll_tab_inner').scrollLeft(currentScrollPos + selectedElementPos)
````

Again, this is not documented use of the plugin, and therefore may not necessarily be supported in future version updates, but even with that disclaimer, there shouldn't be any major reasons to not use the above described method.
