### ISSUE TITLE
How to make it autoscroll slowly in mouse hover?

### ISSUE THREAD

**Issue by suyesh** [joshreed/jQuery-ScrollTabs#11]

**Comment by joshreed** [comment]
I'm assuming you're referring to hovering over the scroll buttons on the left and right, if so you could do something like this:

````
$('#tabSet .scroll_tab_right_button').mouseover(function(e){ $(this).mousedown(); } );
$('#tabSet .scroll_tab_left_button').mouseover(function(e){ $(this).mousedown(); } );
````

Note this would scroll at the same speed as the standard "click" method. If you want to slow down both scrolls, you can set the options (http://joshreed.github.io/jQuery-ScrollTabs/documentation.html) of `scroll_duration` and/or `scroll_distance`. The duration will affect how long it takes to perform the scrolling animation (in milliseconds), and the distance is "how far it will move" in one of those intervals.

If you want to have a separate duration/distance for the hover event, that gets quite a bit more tricky. In that case you maybe would want to just edit the source code yourself, and use your altered version.

If you prefer doing that these are the relevant sections of the codebase:
- https://github.com/joshreed/jQuery-ScrollTabs/blob/master/js/jquery.scrolltabs.js#L149-L167
- https://github.com/joshreed/jQuery-ScrollTabs/blob/master/js/jquery.scrolltabs.js#L169-L187
