### ISSUE TITLE
I added the mousewheel js but the mouse wheel is not working.

### ISSUE THREAD

**Issue by suyesh** [joshreed/jQuery-ScrollTabs#12]
Is there anything specific i need to do to achieve the mouse wheel scroll? I am working on rails project, Everything works fine, just not the mouse wheel

**Comment by joshreed** [comment]
Simply include the conveniently packaged mousewheel JS file in your HTML (or include it in your javascript package if you're doing some form of automated concatenation/minification). The jquery.mousewheel.js file is included in the `js` directory of this repository.

````
  <script src="js/jquery.scrolltabs.js"></script>
  <script src="js/jquery.mousewheel.js"></script>
````

**Comment by joshreed** [comment]
Please refer to the bottom of the documentation page for reference: http://joshreed.github.io/jQuery-ScrollTabs/documentation.html

**Comment by joshreed** [comment]
I just realized you mentioned Rails. Most rails projects use sprockets, so you'd likely need to copy the mousewheel file over to the `vendor/assets/javascripts` directory, and then include it in the `app/assets/javascripts/application.js` file (or a similar file, telling Sprockets what files to concatenate).
