### ISSUE TITLE
Cannot find a way to have visibly hidden tabs

### ISSUE THREAD

**Issue by AlexBezuska** [joshreed/jQuery-ScrollTabs#13]

**Comment by joshreed** [comment]
There are provided the `hideTabs` and `showTabs` functions (please refer to http://joshreed.github.io/jQuery-ScrollTabs/documentation.html for more info on these functions.

**Comment by AlexBezuska** [comment]
My project requires being able to have tabs hidden with the ".hidden" css class, is there a way to have jQuery-ScrollTabs not add the inline style for "display: inline-block" to tabs with class="hidden"?

**Comment by joshreed** [comment]
You can hide the tabs right after initialization using `tabs.hideTabs('.hidden')` which should give you the same effect (where `tabs` is the variable name you assigned to the resulting object). 

Alternatively, you could edit the source code of this plugin to take into account the `hidden` class.
