### ISSUE TITLE
Autoscroll to a certain tab

### ISSUE THREAD

**Issue by AlexBezuska** [joshreed/jQuery-ScrollTabs#14]
Is there a way, or could you point me in the right direction to creating a method like .scrollTo(tabid)
which would tell the scroller to scroll until the desired tab is in the visible part of the nav bar?

I am working on an application where new tabs can be added dynamically while a user is on the page, and we would like to have the user to notice a newly added tab, even if it is int he overflow.

Any direction is super helpful, thanks again!

**Comment by joshreed** [comment]
I actually have an application that is somewhat similar, and the function `tabSet.scrollSelectedIntoView()` already exists to scroll to where the selected tab is visible. Apparently I never added that one to the documentation.

If you need it to not be the selected tab, but rather a tab with a given ID or classname, you can use the methodology found here in the codebase, but swap out some jQuery Selectors:
https://github.com/joshreed/jQuery-ScrollTabs/blob/master/js/jquery.scrolltabs.js#L249-L265

Hopefully this is helpful!
