### ISSUE TITLE
Ability to use a standard <ul> list instead of specific markup

### ISSUE THREAD

**Issue by madhaze** [joshreed/jQuery-ScrollTabs#3]
A lot of menus/tab use <ul> list so it would be nice to be able to apply this to existing menu <ul> without out having to change the markup/rework existing menu markup.

**Comment by joshreed** [comment]
I think this is a great idea, and I plan to begin working on this feature today.

**Comment by joshreed** [comment]
This is fixed by https://github.com/joshreed/jQuery-ScrollTabs/commit/c487404f64bc90ea185ee68fbfd8008f2df67c1d

It is included in the version 2.0.0 release.
