### ISSUE TITLE
Tab Select External Page

### ISSUE THREAD

**Issue by Yaco91** [joshreed/jQuery-ScrollTabs#6]
Hello How could do to make the Tab work for different pages, and so when you load the page is placed in the Tab to select

**Comment by joshreed** [comment]
I assume you're referring to loading a page (i.e. URL) when you click on a tab. If so, then you can refer to http://joshreed.github.io/jQuery-ScrollTabs/documentation.html and the default click_callback function will take the "rel" attribute as a URL.
