### ISSUE TITLE
Position lock of a tab

### ISSUE THREAD

**Issue by ellisgl** [joshreed/jQuery-ScrollTabs#7]
A neat enhancement would be one that you can lock the position of the tab, E.g., the first tab would be locked, and when you scroll, it would be the first tab shown at all times.

**Comment by joshreed** [comment]
That is an interesting idea, and I could see how it could be useful. I will add it to the list of enhancements to be worked on. Also if you feel so inspired, you are welcome to work on it yourself, and create a pull request! I'm always open to collaboration.
