### ISSUE TITLE
Activate tab method.

### ISSUE THREAD

**Issue by ellisgl** [joshreed/jQuery-ScrollTabs#8]
Another enhancement that would be nice.

**Comment by joshreed** [comment]
So if you're trying to figure out what tab is selected, it should be pretty straightforward to handle with simple jQuery, because the `tab_selected` class will be appended to the active tab. For instance: 

    $('#your_scroll_tabs_dom_object').find('.tab_selected')

**Comment by ellisgl** [comment]
No, was thinking more like selecting the tab by id, like clicking on the tab. Which just tells me, I could just fire the click event on the id I gave my element. not elegant, but it work in my quick test. =)

**Comment by joshreed** [comment]
Ah, sorry for misunderstanding! Yeah the firing the click even on your element will work. I'm going to think more about if this would be a useful feature or if it'd just be unnecessary bloat given the ability to handle it with jQuery as-is. If you have any good arguments either way, I'd be happy to hear it.

**Comment by ellisgl** [comment]
Could convert everything to plain javascript and skip jquery, =P
